### ISSUE TITLE
Build fails in RHEL 6.2

### ISSUE THREAD

**Issue by vishnu81** [voiceglue/voiceglue#11]
Hi,

I am trying to install voiceglue on RHEL 6.2 where i have already installed Asterisk 1.8.11.0
It asked for all dependencies which i had installed w/o any issues.

But After that when i gave 'doc/install_voiceglue', 
I got a error in "voiceglue-voiceglue-b12c2a2/openvxi-3.4+vglue/src/log/SBlogMapper.cpp"

<pre><code>
/root/asterisk-src/voiceglue-voiceglue-b12c2a2/openvxi-3.4+vglue/src/log/SBlogMapper.cpp: In member function ‘VXIlogResult SBlogErrorMapper::InitializeXMLParser()’:
/root/asterisk-src/voiceglue-voiceglue-b12c2a2/openvxi-3.4+vglue/src/log/SBlogMapper.cpp:346: error: ‘class xercesc_3_0::SAXParser’ has no member named ‘setDoValidation’
make[1]: *** [build/i386-linux/debug/lib/SBlogMapperD.o] Error 1
make[1]: Leaving directory `/root/asterisk-src/voiceglue-voiceglue-b12c2a2/openvxi-3.4+vglue/src/log'
make: *** [SBlogMapper-shared] Error 2
Build failed in log at ./build_openvxi line 65.
Failed running "./build_openvxi" in "openvxi-3.4+vglue" to install openvxi: No such file or directory at doc/install-voiceglue line 384.
</code></pre>

As per http://svn.apache.org/repos/asf/xml/site/sources/xerces-c/program-sax.xml
I took that these lines can be commented out

<pre>//parser->setDoValidation(false);
//parser->setDoNamespaces(false); </pre>

And then when i ran it second time(after commenting the lines)
i get this error,

<pre><code>
In file included from /root/asterisk-src/voiceglue-voiceglue-b12c2a2/openvxi-3.4+vglue/src/jsi/SBjsi.cpp:48:
/root/asterisk-src/voiceglue-voiceglue-b12c2a2/openvxi-3.4+vglue/src/jsi/JsiRuntime.hpp:94: error: ‘JSGCStatus’ has not been declared
make[1]: *** [build/i386-linux/debug/lib/SBjsiD.o] Error 1
make[1]: Leaving directory `/root/asterisk-src/voiceglue-voiceglue-b12c2a2/openvxi-3.4+vglue/src/jsi'
make: *** [SBjsi-shared] Errohttp://code.google.com/p/stream-tools/wiki/VoiceGluer 2
Build failed in jsi at ./build_openvxi line 80.
Failed running "./build_openvxi" in "openvxi-3.4+vglue" to install openvxi: No such file or directory at doc/install-voiceglue line 384.</code></pre>

Here is more info:

<pre>
Linux ivrs-live 2.6.32-220.el6.x86_64 #1 SMP Wed Nov 9 08:03:13 EST 2011 x86_64 x86_64 x86_64 GNU/Linux
xulrunner-devel-10.0.3-1.el6_2.x86_64
xerces-c-devel-3.0.1-20.el6.x86_64</pre>

PS: I followed this link to install voiceglue
http://code.google.com/p/stream-tools/wiki/VoiceGlue

**Comment by vishnu81** [comment]
guys any update ??

**Comment by voiceglue** [comment]
voiceglue in its currently-released form is not supported on CentOs/RHEL 6.
We hope to release a newer version that supports that OS soon.
However, it is possible to build the current version.

The difficulty is that these OSes have a newer version of Xerces-C.
This version has an API incompatible with that expected by OpenVXI.

The solution (until an officially supported version of voiceglue is available)
is to install the 2.8 version of Xerces-C in place of the default 3.0 version.
I have only done this by building it from source,
but I assume it is also possible to use a packaged version.

**Comment by vishnu81** [comment]
Hi,

Thanks for the reply, I downgraded the xerces using RPMS here http://mirror.centos.org/centos/5/extras/x86_64/RPMS/
That resolved the first error.
but the 'JSGCStatus'  not declared issue is still there.
Probably, i will have to downgrade xulrunner too.
Let me try that and get back to you.

**Comment by vishnu81** [comment]
Nope,

I downgraded xulrunner-10.0.3-1 to 10.0.1-2 using http://mirror.centos.org/centos/5/updates/x86_64/RPMS/
But it didnt help.
Same error.
What do u suggest then?

**Comment by vishnu81** [comment]
Any other workaround u suggest?
I would like to stick to the voiceglue, which i have become much familiar with.
I had no issues with installing it on 32-bit Centos and 64-bit Ubuntu
Please let me know ASAP wht can be done

**Comment by vishnu81** [comment]
Ok guys, issue resolved .
I took the version of xulrunner installed for the centos 5 and installed the same here.
xulrunner-1.9.2.26-1.el5_7.x86_64.rpm from http://mirror.centos.org/centos/5/os/x86_64/CentOS/
Voiceglue installed !!

But I suppose this workaround is safe, right??

**Comment by zoommac** [comment]
Thanks....for xulrunner-1.9.2.26-1.el5_7.x86_64.rpm.

R's,
Amit Shukla
